name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # hoặc 'master' tùy bạn dùng branch nào

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload site
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # deploy toàn bộ repo

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
